package Exception;

public class Exce_1 {
//	
//	int a =10, b=0;
//	public Exce_1() {
//	try {
//		int c =a/b;
//		System.out.println(c);
//	}catch(ArithmeticException e) {
//		System.out.println(e);
//	}
//	}
	
//	int arr[]= new int[3];
//	public Exce_1() {
//	try {
//		System.out.println(arr[6]);
//	}catch(ArrayIndexOutOfBoundsException e) {
//		System.out.println(e);
//	}
//	}

	
//	public Exce_1() {
//			try {
//				try {
//				int a =10,b=0;
//				int c =a/b;
//				System.out.println(c);
//				}catch(ArithmeticException e) {
//					System.out.println(e);
//				}
//				int arr[]=new int[3];
//				System.out.println(arr[6]);
//			}catch(ArrayIndexOutOfBoundsException e) {
//				System.out.println(e);
//			}
//				
//	}
	
	public Exce_1() {
	try {
			String s ="hello";
			int i = Integer.parseInt(s);
			System.out.println(i);
	}catch(NumberFormatException e) {
		System.out.println(e);
	}
	
	int i =10;
	String c= String.valueOf(i);		
	System.out.println(c);			
	}
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		new Exce_1();
	}

}




package Exception;

public class finally_keyword {
	
	public finally_keyword() {
		int a =10;
		int b = 0;
		try {
			int c =a/b;
			System.out.println(c);
		}catch(ArithmeticException e) {
			System.out.println(e);
		}finally {
			System.out.println("This is final block");
		}
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		finally_keyword s = new finally_keyword();
	}

}




package Exception;

public class throw_keyword {
	
	
	public throw_keyword() throws Exception{
		int i =10;
		if(i>10) {
			System.out.println(i);
		}else {
			throw new Exception("Invalid number");
		}
	}

	public static void main(String[] args) throws Exception{
		throw_keyword s = new throw_keyword();
		

	}

}




package Exception;
class Custom_check extends Exception{
	public Custom_check(String s) {
	super(s);
	}
}
public class custom_exception  {
	
public custom_exception() throws Custom_check {
	int i =11;
	if(i>10) {
		System.out.println(i);
	}else {
		throw new Custom_check("Invalid number");
	}
}	
	public static void main(String[] args) throws Custom_check{
		custom_exception s = new custom_exception();
		// TODO Auto-generated method stub

	}

}





package Exception;

import java.util.Scanner;

class insufficient_fund extends Exception{
	public insufficient_fund(String s ) {
	super(s);
	}
}
public class Bank  {
	int balance;
	int amount;
	Scanner sc = new Scanner(System.in);
	void deposit() throws insufficient_fund {
		System.out.println("Enter deposit :");
		 balance = sc.nextInt();
		if (balance >0) {
			System.out.println("Your balance is : "+ balance);
		}else {
			throw new insufficient_fund("Deposit your amount");
		}
	}
	
	void withdraw() throws insufficient_fund {
System.out.println("Enter amount you want to withdraw : ");
	amount = sc.nextInt();
		if(balance > amount) {
			System.out.println("Withdrawl amount is  " + amount);
		}else {
			throw new insufficient_fund("Invalid withdrawl amount");
		}
	}
	public static void main(String[] args) throws insufficient_fund {
		Bank b = new Bank();
		b.deposit();
		b.withdraw();
	}

}
